### ISSUE TITLE
Create website with new UI

### ISSUE THREAD

**Issue by mikeparker** [mikeparker/prcreator#5]
I'll open a separate issue for using a different authentication method.

**Comment by chrispatrick** [comment]
Out of interest, which version of VS do you use? Considering trying ASP.NET 5 but it needs VS2015 so I may just stick with 4.6 for now.

**Comment by mikeparker** [comment]
As you can probably tell from the solution file, I'm on 2012 at home. I did start working with 2015 but i couldnt stand no resharper and I couldnt be bothered to work out what the latest resharper I have a licence for is, and whether i can use a work license etc so I just went with 2012. If we need to use 2015 its probably not a big deal though, i'm sure i can set it up.

**Comment by chrispatrick** [comment]
Fair enough. Don't think I have R# at home either way. I'm not too fussed. Unsure whether I want to go through the stress of figuring out how all the beta vNext stuff works...
